### ISSUE TITLE
单独点亮HDMI

### ISSUE THREAD

**Issue by SamCsquared** [oreoft/EFI_deskimini-h470#1]
您好：不知道能否分享一下让单独点亮HDMI您做了甚麽改变呢?我试图抄您的deviceproperty参数和nvram boot arg却无法单独点亮HDMI，但直接套用您的EFI却可以成功点亮HDMI，另外您的con0和con2照理说已经是DP display port应该不用再patch了?不知道删除相关参数是否您的萤幕同时使用就不会闪屏了呢?万分感谢

**Comment by oreoft** [comment]
是否能告知您的平台，方便我给您意见，我这个EFI实际上已经可以单独点亮HDMI，目前我就在用单显示器通过HDMI外接。理论上来说UHD想要单独使用HDMI应该设置enable-hdmi-dividers-fix和enable-hdmi20修复缓冲帧或者定制显示器EEID来实现。关于显示器同时会闪屏问题，目前已经没有显示器来进行测试了，后期有机会再进行修复。感谢关注。

**Comment by SamCsquared** [comment]
您好：
我的平台跟您一样，也是华擎的deskmini h470，只是CPU是i3-10100，使用的萤幕是一般的FHD用HDMI，自己之前尝试看教程做OC 7.2唯独只能用DP不能用HDMI单独点亮，Big Sur灌完之后我用您的EFI当开机USB碟的确是可以单独点亮HDMI的，唯独我不懂为什麽我複製贴上您的数据(con patch)到我自己建的OC就不行

**Comment by oreoft** [comment]
应该是高版本OC需要做其他调整，您可以尝试注入显示器的EDID值，我相信注入了以后单DHMI可以正常输出的。具体可以参考小兵的这篇[文章](https://blog.daliansky.net/Use-HIDPI-to-solve-sleep-wake-up-black-screen,-Huaping-and-connect-the-external-monitor-the-correct-posture.html)
