### ISSUE TITLE
目前蓝牙正常了么？

### ISSUE THREAD

**Issue by jiyuefeng** [oreoft/EFI_deskimini-h470#2]
之前设置机型为macmini8,1 怎么打驱动都无法识别，无论是BCM94352Z、还是BCM943602CS，头大。看到你这个提醒，明天我再试试。

**Comment by oreoft** [comment]
隐藏bug，设置imac20.1包好😂

**Comment by oreoft** [comment]
> 之前设置机型为macmini8,1 怎么打驱动都无法识别，无论是BCM94352Z、还是BCM943602CS，头大。看到你这个提醒，明天我再试试。

隐藏bug，设置imac20.1包好😂

**Comment by jiyuefeng** [comment]
试过了imac20,1 imac20,2 蓝牙均不识别，USB总线那里也看不到控制器。是不是没救了？

**Comment by oreoft** [comment]
> 

看不到控制器，USB没有定制吗。蓝牙是走usb2.0的，如果EFI没有定制USB系统是没办法检测到这个硬件，就更别说驱动了
方法可以参考一下小兵的[博客文章](https://blog.daliansky.net/Intel-FB-Patcher-USB-Custom-Video.html)

**Comment by jiyuefeng** [comment]
定制过了，不过我不清楚我的定制是否正确。因为我使用hacktool工具界面，依然看不到蓝牙的链接设备。

**Comment by oreoft** [comment]
> 定制过了，不过我不清楚我的定制是否正确。因为我使用hacktool工具界面，依然看不到蓝牙的链接设备。

用我的EFI试过了吗，如果是同机型的话可以替换一下我的EFI，或者把您的EFI给我看看。我使用的也是BCM943602CS，并且使用10.15.x版本是可以设置成macmini的并且蓝牙可以驱动
![image](https://user-images.githubusercontent.com/51789848/143547295-201d4e97-0c28-4eab-9894-177dc4ed0c05.png)

**Comment by jiyuefeng** [comment]
用过了你的efi 用的是0.9.5那个版本。不过我的配置和你的还是有些许差异，我的是I3-10100的CPU，macOS版本也是10.15.7 。你这个版本的OC是哪个版本？

**Comment by jiyuefeng** [comment]
> 
![image](https://user-images.githubusercontent.com/6139209/143547996-de5f600d-db1b-4bf2-ad5b-3135e384a7dc.png)

**Comment by jiyuefeng** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/6139209/143547996-de5f600d-db1b-4bf2-ad5b-3135e384a7dc.png)

USB定制，如果正常的话，是不是应该会显示一个BCM的博通蓝牙控制器？

**Comment by jiyuefeng** [comment]
天啊。 用了你的最新版本的0.9.7版本的 蓝牙成了！！！！

**Comment by oreoft** [comment]
> ，

have fun~

**Comment by oreoft** [comment]
> 天啊。 用了你的最新版本的0.9.7版本的 蓝牙成了！！！！

have fun~
