### ISSUE TITLE
请问楼主这个支持到那个系统？big sur还是？

### ISSUE THREAD

**Issue by twotreeszf** [oreoft/EFI_deskimini-h470#4]

**Comment by oreoft** [comment]
我自己办公用10.15.7 (19H1615)，我觉得bigsur往后都是m1优化的多一点，我oc版本一直没升级，高版本引导界面有点卡的bug一直没解决。所以oc版本是6.4，最高支持到catalina(理论上可以bigsur，但是蓝牙会有bug)
